Hw02 express
kosta-j/nodejs-homework-rest-api pull request #1
Opened 2021-11-02 06:38 UTC by kosta-j

2021-11-02 21:03 UTC, TViglesGoom requested changes

2021-11-02 21:03 UTC, TViglesGoom commented on model/index.js
> +    (item) => String(item.id) === contactId
Зачем приводить айди к строке? Вы не знаете, какой там лежит тип данных?

2021-11-02 21:03 UTC, TViglesGoom commented on model/index.js
> +  const contactToDeleteIdx = contacts.indexOf(contactToDelete)
Вы один раз прошлись по массиву, нашли элемент. А потом второй раз прошлись по массиву, нашли его индекс. Может быть можно найти индекс и по индексу достать этот элемент?

2021-11-02 21:03 UTC, TViglesGoom commented on routes/api/contacts.js
> +  name: Joi.string().min(3).required(),
Ян

2021-11-02 21:03 UTC, TViglesGoom commented on routes/api/contacts.js
> +    const { error } = joiSchema.validate(updatedContact)
Используйте миддлвары для валидации тела запроса

2021-11-02 21:03 UTC, TViglesGoom commented on routes/api/contacts.js
> +      throw new BadRequest('missing fields')
Какие именно поля отсутствуют. Честно говоря, мне вот непонятно. Да и к тому же, а разве по ТЗ на пут запрос мы обязаны передавать все поля, а не только те, что хотим изменить?

2021-11-02 21:03 UTC, TViglesGoom commented on routes/api/contacts.js
> +      throw new NotFound('Not found')
Выбрасываем ошибку, чтобы сразу её отловить? Вы не знаете, что делать, если нет такого контакта?

2021-11-02 21:03 UTC, TViglesGoom commented on routes/api/contacts.js
> +      code: 200,
Зачем вы дублируете статус код в теле ответа?

2021-11-02 21:03 UTC, TViglesGoom commented on model/index.js
> +    (item) => String(item.id) === contactId
Зачем приводить айди к строке

2021-11-02 21:03 UTC, TViglesGoom commented on model/index.js
> +  const index = contacts.findIndex((item) => item.id === contactId)
Почему здесь не приводите айди к строке? Это было делать не обязательно в вашей реализации?

2021-11-03 07:40 UTC, kosta-j commented on model/index.js
> +    (item) => String(item.id) === contactId
Потому что в ID исходных контактов был number, а в новых ID генерится string. И в http запросе id это string.
Сделал айдишники исходных контактов строками и убрал приведение к строке, согласно вашей рекомендации в слак

2021-11-03 07:58 UTC, kosta-j commented on model/index.js
> +  const contactToDeleteIdx = contacts.indexOf(contactToDelete)
Переделал - теперь 1 проход
```suggestion
  const contacts = await readData()
  const contactToDeleteIdx = contacts.findIndex((item) => item.id === contactId)
  const removed = contacts.splice(contactToDeleteIdx, 1)
  await writeData(contacts)

  return removed
}
```

2021-11-03 08:42 UTC, kosta-j commented on routes/api/contacts.js
> +  name: Joi.string().min(3).required(),
fixed

2021-11-03 09:35 UTC, kosta-j commented on routes/api/contacts.js
> +    const { error } = joiSchema.validate(updatedContact)
done

2021-11-03 10:10 UTC, kosta-j commented on routes/api/contacts.js
> +      throw new BadRequest('missing fields')
убрал error...
По поводу required полей. - Как я понял из спецификации - PUT запрос в отличии от PUTCH должен заменить всю сущность. Если передать не все поля - он заменить весь объект на тот, что передали. А чтобы обновлять сущность - нужно делать PATCH.

![image](https://user-images.githubusercontent.com/75508339/140040806-666a6d4d-7b6b-4843-a917-3b857a0b53f0.png)

В ТЗ исходниках было странное расхождение - в readme(необходимый список раутов) указан PUT, но написано при этом про обновление полей . 
Насколько я понял, надо или делать раут PUT и передавать ему весь объект, или делать раут PATCH и передавать только обновленные данные. Я сделал по первому асампшену.

В принципе у меня опыта особо не много и я наверное сделал не правильные выводы. Поправьте меня плиз, если так

2021-11-03 10:15 UTC, kosta-j commented on model/index.js
> +    (item) => String(item.id) === contactId
fixed

2021-11-03 10:16 UTC, kosta-j commented on model/index.js
> +  const index = contacts.findIndex((item) => item.id === contactId)
это был баг ))  - уже убрал отовсюду метод String

2021-11-03 10:28 UTC, kosta-j commented on routes/api/contacts.js
> +      throw new NotFound('Not found')
Этот подход нам давал Богдан на практике. Идея в том, чтобы прокидывать все ошибки в одну мидлвару в app.js. Лучше делать ретурн?
if (!result) {
        const notFound = new NotFound('Not found')
        return notFound
      }

2021-11-03 10:50 UTC, kosta-j commented on routes/api/contacts.js
> +      code: 200,
Делали так на практике, убрал

2021-11-06 10:20 UTC, TViglesGoom commented on routes/api/contacts.js
> +      throw new NotFound('Not found')
Это очень холиварная тема, я считаю. Но большая проблема ошибок в том, что они создают во-первых - не совсем очевидное передение, во-вторых, значительно замедляют работа приложения. В данном случае будет незаметно, но если строить действительно что-то масштабное, то вы это заметите.

2021-11-06 10:23 UTC, TViglesGoom commented on routes/api/contacts.js
> +      throw new BadRequest('missing fields')
Да, вы абсолютно правы! Не обратил на это внимание, смотрел только на то, что в тз обновление любых полей стоит. Оба варианты, которые вы предложили - правильные.

2021-11-06 10:23 UTC, TViglesGoom approved these changes

2021-11-06 11:46 UTC, kosta-j commented on routes/api/contacts.js
> +      throw new NotFound('Not found')
Got it. Благодарю!

2021-11-06 11:46 UTC, merged