Hw05 avatars
kosta-j/nodejs-homework-rest-api pull request #4
Opened 2021-11-29 10:46 UTC by kosta-j

2021-11-29 22:40 UTC, KirillKulakow commented on controllers/auth/signUp.js
> +    const avatarURL = gravatar.url(email, { d: 'identicon' })
добавь опцию протокола

2021-11-29 22:41 UTC, KirillKulakow commented on controllers/auth/updateAvatar.js
> +    if (!mimetype.includes('image')) {
это можно перенести в мидлвару

2021-11-29 22:42 UTC, KirillKulakow requested changes
need fix

2021-11-30 06:25 UTC, kosta-j commented on controllers/auth/signUp.js
> +    const avatarURL = gravatar.url(email, { d: 'identicon' })
fixed

2021-11-30 07:16 UTC, kosta-j commented on controllers/auth/updateAvatar.js
> +    if (!mimetype.includes('image')) {
moved

2021-11-30 21:06 UTC, KirillKulakow approved these changes

2021-12-01 06:35 UTC, merged